### ISSUE TITLE
Using mod.info instead of separate file

### ISSUE THREAD

**Issue by rm-code** [blind-coder/pz-tiny_avc#1]
I was wondering if we could use the mod.info file instead of depending on another separate file.

```
name=tiny Automated Version Checker
poster=empty.png
description=Automated mod version checker.
url=http://theindiestone.com/forums/index.php/topic/13014-
id=tiny_avc

version:1.4.0
pzversion:32.2
version_info: http://pzmap.crash-override.net/tiny_avc.txt
```

If you are interested, I could work on a PR.

Best wishes,
Robert

**Comment by blind-coder** [comment]
Yes, we can use that. I talked to RJ and "unknown" entries in mod.info are simply ignored.

We should use the key=value format, too, instead of key:value to keep the syntax intact (or maybe support both?)
getModInfo will NOT return these values, but tiny_avc still needs to read and parse mod.info itself.

PR always welcome :-)

**Comment by rm-code** [comment]
Already working on it :smile: :+1:

```
modversion=0.7.0
pzversion:32.2
versionurl=https://raw.githubusercontent.com/blind-coder/pz-tiny_avc/master/latest_version.txt
modurl=http://theindiestone.com/forums/index.php/topic/13014-tiny-automated-version-checker-tiny-avc-070/
```

These are the tags I'd use. (I think the modurl could be omitted though - IIRC the vanilla mod.info already has a url tag).

**Comment by blind-coder** [comment]
The original intent of the modurl was to point to a download location, but that might not be necessary. I'd change some behaviour so that if modurl is missing, url is used instead.

**Comment by rm-code** [comment]
Sounds good to me.

**Comment by rm-code** [comment]
[Pull request](https://github.com/blind-coder/pz-tiny_avc/pull/2) is online. It still needs some testing.

**Comment by rm-code** [comment]
Seems to work on my end.
